### ISSUE TITLE
publish simple data from ESP32 ?

### ISSUE THREAD

**Issue by dangviethieu** [opendroneid/opendroneid-core-c#27]
Hi all. I wrote a simple code in Arduino IDE to test ESP32 and publish sample data from test/odidtest. But the receiver-android app cannot scan and detect that signals.
I use "Serial Bluetooth Terminal" in Android, it received that signals.
This is my code 🙇 
#include "BluetoothSerial.h"
#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif
BluetoothSerial SerialBT;
void setup() {
  Serial.begin(115200);
  SerialBT.begin("ESP32test"); //Bluetooth device name
  Serial.println("The device started, now you can pair it with bluetooth!");
}
void loop() {
    SerialBT.print("00 12 49 4e 54 43 45 31 32 33 34 35 36 37 38 39 30 31 32 33 34 35 00 00 00");
    delay(1000);
    SerialBT.print("10 24 5a 2c 04 44 bf 24 1b 52 d5 b4 b6 98 08 98 08 34 08 5b 44 58 02 05 00");
    delay(1000);
    SerialBT.print("20 10 01 0c c0 f3 5e 01 30 33 30 61 30 63 64 30 33 33 61 33 00 00 00 00 00");
    delay(1000);
    SerialBT.print("30 00 52 65 61 6c 20 45 73 74 61 74 65 20 50 68 6f 74 6f 73 00 00 00 00 00");
    delay(1000);
    SerialBT.print("40 04 3a bf 24 1b 74 d1 b4 b6 23 00 07 31 09 23 08 24 00 00 00 00 00 00 00");
    delay(1000);
    SerialBT.print("50 00 39 38 37 36 35 34 33 32 31 30 30 31 32 33 34 35 36 37 38 39 00 00 00");
    delay(1000);
}
Thanks very much!

**Comment by friissoren** [comment]
I personally don't have any experience using the ESP32. However, I suspect that you might have run into a similar problem as  already earlier discussed here:
https://github.com/opendroneid/receiver-android/issues/7

Please read through that. If that doesn't help you, let me know and we can then dive a bit deeper.

BTW: If I have understood correctly, the ESP32 HW only supports normal legacy advertising mode for Bluetooth, and not the optional BT5.0 Long Range and Extended Advertising modes (https://www.espressif.com/en/news/BLE_5.0_Certification). This means that the maximum transmit/receive range you will be able to achieve is somewhat limited (maybe up to 250 meters in ideal conditions).
However, since we currently don't have any open source implementation demonstrating the Bluetooth FW for open drone ID, if you at some point get your FW to work properly, I would be interested in hearing about it and if you are willing, we could add the source codes for that as a separate repository to the opendroneid Github project.
